# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import estimator_pb2 as estimator__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in estimator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EstimatorServiceStub(object):
    """EstimatorService translates kernel telemetry feature vectors
    into estimated energy consumption (joules).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Estimate = channel.unary_unary(
                '/ecobpf.estimator.v1.EstimatorService/Estimate',
                request_serializer=estimator__pb2.FeatureVectorBatch.SerializeToString,
                response_deserializer=estimator__pb2.EnergyEstimateBatch.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ecobpf.estimator.v1.EstimatorService/HealthCheck',
                request_serializer=estimator__pb2.HealthRequest.SerializeToString,
                response_deserializer=estimator__pb2.HealthResponse.FromString,
                _registered_method=True)


class EstimatorServiceServicer(object):
    """EstimatorService translates kernel telemetry feature vectors
    into estimated energy consumption (joules).
    """

    def Estimate(self, request, context):
        """Estimate processes a batch of feature vectors and returns
        per-process energy estimates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck verifies the ML model is loaded and ready.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EstimatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Estimate': grpc.unary_unary_rpc_method_handler(
                    servicer.Estimate,
                    request_deserializer=estimator__pb2.FeatureVectorBatch.FromString,
                    response_serializer=estimator__pb2.EnergyEstimateBatch.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=estimator__pb2.HealthRequest.FromString,
                    response_serializer=estimator__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ecobpf.estimator.v1.EstimatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ecobpf.estimator.v1.EstimatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EstimatorService(object):
    """EstimatorService translates kernel telemetry feature vectors
    into estimated energy consumption (joules).
    """

    @staticmethod
    def Estimate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecobpf.estimator.v1.EstimatorService/Estimate',
            estimator__pb2.FeatureVectorBatch.SerializeToString,
            estimator__pb2.EnergyEstimateBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecobpf.estimator.v1.EstimatorService/HealthCheck',
            estimator__pb2.HealthRequest.SerializeToString,
            estimator__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
